DROP DATABASE IF EXISTS whatever;

CREATE DATABASE whatever;

USE whatever;

CREATE TABLE users (
    id INT AUTO_INCREMENT NOT NULL,
    is_paying BOOL DEFAULT 0,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE whatever (
	id INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (id)
)

